version: "3"
services:
  express-server:
    image: ${DOCKERHUB_NAME}/${IMAGE_NAME}:${IMAGE_VERSION}
    container_name: ${IMAGE_NAME}
    env_file: .env
    environment:
      ENVIRONMENT: production
      NODE_ENV: production
    ports:
      - "${EXPRESS_HOST_PORT}:${EXPRESS_CONTAINER_PORT}"
    networks:
      - my-app-network
networks:
  my-app-network:
